Resources:
  MySecureInstance:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
      SecurityGroups:
        # we reference the output from another stack here using the Fn::ImportValue function.
        # SSHSecurityGroup - is the unique global value, output of one of CF stacks that can be used by other stacks
        - !ImportValue SSHSecurityGroup
